use_frameworks!

target 'Lottie-Example' do
  pod 'lottie-ios', :path => 'victoriafeng/Desktop/'

  target 'lottie-ios_Tests' do
    inherit! :search_paths

    
  end
end

target 'Lottie Viewer' do
  pod 'lottie-ios', :path => 'victoriafeng/Desktop/'
end