# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lottie_iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lottie_iOS

end

target 'Lottie_macOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lottie_macOS

end

target 'Lottie_tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lottie_tvOS

end

target 'LottieLibraryIOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LottieLibraryIOS

end

target 'LottieLibraryMacOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LottieLibraryMacOS

end
